### PR TITLE
Removed lea from hosts

### PR DESCRIPTION
**Pull request by Pfonks**

### CODE REVIEW

**Comment by primeos** [comment]
I assume lea was decommissioned after the PPI moved to Docker? Would be nice if the reason was part of the commit message (a brief sentence would be sufficient).
Anyway, the more important thing is that we should keep the files consistent and there are additional occurrences (git-grep is useful for that):
```
ssh/fsi-run-everywhere:for host in "amy" "anja" "kim" "lara" "lea" "nina" "sessel" "sofa" "teri" "trinity"; do
ssh/fsi_hosts:u-220-c-lea.fsi.uni-tuebingen.de,lea.fsi.uni-tuebingen.de,ppi.fsi.uni-tuebingen.de,134.2.220.50 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBSOQGH6l0VAEMEntFTg8yuoArX7I8ml51Ok/KXM4jeDBt0emoaqqllwlanAh3lV00R6eJCniFcObCfjfzHD1xVMluQd08YP6Y7WDjev60DWADanrDcb+qNvP5SHPiPI0Nq9688gKliWqELZrtyZ7Ae+D5/Z3oO1P5BHRtlFqYUbp8IuzjDk/xHxkH2zcWAaGdkgaWjyCr4KJeLgxmB0eHK7Lw36hzzQ73MztPjJoBg+ZvrTorCwP8ISdLkTqQF1/dt3CZdvNti1FC7H22VzpBU5+jyRGwu7uYNCjM24cKe6j5XnZQqY29FBW1OP2RZm6rrm8FObbMeVfovdaF/rnN
```

**Comment by luoe** [comment]
Thanks @primeos for having a look :)

**Comment by Pfonks** [comment]
Sorry and fixed :)

**Comment by primeos** [comment]
No problem and thanks for the fix (#2) :)

**Pull request merged**
